name: Super-Linter

on: push

jobs:
  lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node@16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Eslint dependencies
        run: yarn add -D eslint eslint-config-react-app eslint-plugin-react-hooks

      - name: Run linter
        run: yarn lint

        #uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  tsc:
    name: TSC code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node@16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Eslint dependencies
        run: yarn

      - name: Run tsc check
        run: yarn tsc
